name: Tester
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  PHPUnit:
    name: ${{ matrix.os }}-php${{ matrix.php-version }}-${{ matrix.framework }}
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        framework:
          - default
          - laravel
          - hyperf
        php-version:
          - 7.4
          - 8.0
          - 8.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: openssl
          coverage: none
      - name: Laravel Framework
        if: matrix.framework == 'laravel'
        run: composer require illuminate/container
      - name: Hyperf Framework
        if: matrix.framework == 'hyperf'
        run: composer require hyperf/utils php-di/php-di -W
      - name: Other/No Framework
        if: matrix.framework == 'default'
        run: composer require php-di/php-di
      - name: Run PHPUnit
        run: composer test
