name: Tester
on: [push, pull_request]

jobs:
  PHPUnit:
    name: ${{ matrix.os }}-php${{ matrix.php-version }}-${{ matrix.framework }}
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        framework:
          - default
          - laravel
          - thinkphp
          - hyperf
        php-version:
          - 7.4
          - 8.0
          - 8.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: openssl
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Laravel Framework
        if: matrix.framework == 'laravel'
        run: rm -rf composer.lock && composer require illuminate/container -W
      - name: ThinkPHP Framework
        if: matrix.framework == 'thinkphp'
        run: rm -rf composer.lock && composer require topthink/think-container -W
      - name: Hyperf Framework
        if: matrix.framework == 'hyperf'
        run: rm -rf composer.lock && composer require hyperf/utils -W
      - name: Other/No Framework
        if: matrix.framework == 'default'
        run: rm -rf composer.lock && composer require php-di/php-di -W
      - name: Run PHPUnit
        run: composer test
