name: Tester
on: [push, pull_request]

jobs:
  PHPUnit:
    name: php-${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php-version:
          - 7.3
          - 7.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: openssl
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Run PHPUnit
        run: composer test
